In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sample-data/phase_data_sample.csv


***Reading the data using Pandas***

In [2]:
df = pd.read_csv('/kaggle/input/sample-data/phase_data_sample.csv',index_col=None)

In [3]:
df.index


RangeIndex(start=0, stop=17337, step=1)

In [4]:
df.head()

0         1         2         3         4         5         6  \
0 -2.431423  1.483793 -1.161452  1.791645  0.270695 -0.089481  0.356688   
1 -2.811765  0.697328 -2.056736  0.978536 -0.911127 -0.973984 -1.916140   
2 -0.103309 -0.413561  0.030206 -0.230614 -0.200565 -0.235467  0.078330   
3  3.701616 -1.404758 -1.796171  0.263228  0.142206 -0.327979  0.078298   
4  1.598397 -0.165481  1.795930  0.755155 -0.604168 -0.633534 -1.055088   

          7         8         9  ...       125       126       127       128  \
0  1.632386 -0.572265  0.099085  ... -0.415398 -0.452132 -0.360327 -0.159069   
1  0.007252  1.290173 -1.655500  ... -0.415398 -0.215571  0.263873 -0.159069   
2  0.601497  0.102205  0.044518  ... -0.415398  0.115614 -0.776461 -0.159069   
3  0.339293 -2.803031  0.851896  ...  1.510721  0.115614  2.344540 -0.159069   
4 -0.442009  1.344237 -0.536694  ... -0.415398 -0.357508 -0.776461 -0.159069   

        129       130       131       132       133  label  
0 -0.338560 -0.322463 -0.143152 -1.080384  0.538832      0  
1 -0.338560 -0.322463 -0.143152 -0.973158  0.538832      1  
2  1.815429 -0.322463 -0.143152 -0.865932  0.538832      8  
3  1.456431 -0.322463 -0.143152 -0.758705  0.538832      5  
4 -0.338560 -0.322463 -0.143152 -0.651479  0.538832      9  

[5 rows x 135 columns]

In [5]:
df.describe()

0             1             2             3             4  \
count  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04   
mean  -1.598383e-17  1.475430e-17  4.098418e-18  3.442671e-17 -8.401757e-18   
std    1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00   
min   -5.434302e+00 -4.597059e+00 -3.958322e+00 -5.303061e+00 -4.765904e+00   
25%   -5.485141e-01 -4.135612e-01 -7.217110e-01 -6.856549e-01 -6.041680e-01   
50%   -1.033089e-01 -1.654807e-01  3.020581e-02 -2.306139e-01 -4.765512e-02   
75%    6.825683e-01  6.761393e-01  5.940180e-01  7.551551e-01  7.246876e-01   
max    5.364742e+00  4.301265e+00  3.624895e+00  5.653327e+00  4.097894e+00   

                  5             6             7             8             9  \
count  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04   
mean  -2.008225e-17 -1.209033e-17  4.344323e-17 -4.344323e-17 -2.172162e-17   
std    1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00   
min   -5.394728e+00 -3.663934e+00 -3.798895e+00 -3.573673e+00 -4.145909e+00   
25%   -5.062800e-01 -7.264551e-01 -5.607783e-01 -4.443186e-01 -5.366939e-01   
50%   -1.944864e-01  6.317305e-02  1.489618e-01  1.022050e-01  4.451785e-02   
75%    7.051203e-01  5.330219e-01  6.014967e-01  4.573735e-01  3.669932e-01   
max    5.261173e+00  4.118938e+00  4.699579e+00  5.217108e+00  5.143999e+00   

       ...           125           126           127           128  \
count  ...  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04   
mean   ...  3.125044e-17  2.950861e-17  2.090193e-17  2.090193e-17   
std    ...  1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00   
min    ... -4.153984e-01 -4.994447e-01 -7.764608e-01 -1.590691e-01   
25%    ... -4.153984e-01 -4.284763e-01 -7.764608e-01 -1.590691e-01   
50%    ... -4.153984e-01 -2.865396e-01 -1.522606e-01 -1.590691e-01   
75%    ... -4.153984e-01 -7.363456e-02  2.638728e-01 -1.590691e-01   
max    ...  2.751334e+01  1.376519e+01  2.148668e+01  1.193646e+01   

                129           130           131           132           133  \
count  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04  1.733700e+04   
mean   6.475501e-17 -2.541019e-17  1.250018e-17 -4.918102e-18 -6.106643e-17   
std    1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00  1.000029e+00   
min   -3.385603e-01 -3.224627e-01 -1.431520e-01 -1.080384e+00 -1.855868e+00   
25%   -3.385603e-01 -3.224627e-01 -1.431520e-01 -7.587053e-01  5.388315e-01   
50%   -3.385603e-01 -3.224627e-01 -1.431520e-01 -2.225734e-01  5.388315e-01   
75%   -3.385603e-01 -3.224627e-01 -1.431520e-01  4.207848e-01  5.388315e-01   
max    2.838129e+01  7.367408e+00  3.167513e+01  6.854367e+00  5.388315e-01   

              label  
count  17337.000000  
mean       5.964527  
std        4.172304  
min        0.000000  
25%        1.000000  
50%        5.000000  
75%        9.000000  
max       16.000000  

[8 rows x 135 columns]

In [6]:
df.isnull()


0      1      2      3      4      5      6      7      8      9  \
0      False  False  False  False  False  False  False  False  False  False   
1      False  False  False  False  False  False  False  False  False  False   
2      False  False  False  False  False  False  False  False  False  False   
3      False  False  False  False  False  False  False  False  False  False   
4      False  False  False  False  False  False  False  False  False  False   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
17332  False  False  False  False  False  False  False  False  False  False   
17333  False  False  False  False  False  False  False  False  False  False   
17334  False  False  False  False  False  False  False  False  False  False   
17335  False  False  False  False  False  False  False  False  False  False   
17336  False  False  False  False  False  False  False  False  False  False   

       ...    125    126    127    128    129    130    131    132    133  \
0      ...  False  False  False  False  False  False  False  False  False   
1      ...  False  False  False  False  False  False  False  False  False   
2      ...  False  False  False  False  False  False  False  False  False   
3      ...  False  False  False  False  False  False  False  False  False   
4      ...  False  False  False  False  False  False  False  False  False   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
17332  ...  False  False  False  False  False  False  False  False  False   
17333  ...  False  False  False  False  False  False  False  False  False   
17334  ...  False  False  False  False  False  False  False  False  False   
17335  ...  False  False  False  False  False  False  False  False  False   
17336  ...  False  False  False  False  False  False  False  False  False   

       label  
0      False  
1      False  
2      False  
3      False  
4      False  
...      ...  
17332  False  
17333  False  
17334  False  
17335  False  
17336  False  

[17337 rows x 135 columns]

In [7]:
df.dropna(how='any')

0         1         2         3         4         5         6  \
0     -2.431423  1.483793 -1.161452  1.791645  0.270695 -0.089481  0.356688   
1     -2.811765  0.697328 -2.056736  0.978536 -0.911127 -0.973984 -1.916140   
2     -0.103309 -0.413561  0.030206 -0.230614 -0.200565 -0.235467  0.078330   
3      3.701616 -1.404758 -1.796171  0.263228  0.142206 -0.327979  0.078298   
4      1.598397 -0.165481  1.795930  0.755155 -0.604168 -0.633534 -1.055088   
...         ...       ...       ...       ...       ...       ...       ...   
17332 -0.103309 -0.413561  0.030206 -0.230614 -0.200565 -0.235467  0.078330   
17333  1.913463 -0.928488 -0.449048 -0.094250 -1.940294  0.322556  1.699141   
17334 -0.548514  0.277013 -1.669528 -0.860531  1.283522  0.859646  0.774062   
17335  2.021756  0.121105  0.286161 -0.913391  0.984242  0.491924 -0.900117   
17336 -0.710822  1.288865  0.918858  0.882426  0.851136  0.441219  0.019907   

              7         8         9  ...       125       126       127  \
0      1.632386 -0.572265  0.099085  ... -0.415398 -0.452132 -0.360327   
1      0.007252  1.290173 -1.655500  ... -0.415398 -0.215571  0.263873   
2      0.601497  0.102205  0.044518  ... -0.415398  0.115614 -0.776461   
3      0.339293 -2.803031  0.851896  ...  1.510721  0.115614  2.344540   
4     -0.442009  1.344237 -0.536694  ... -0.415398 -0.357508 -0.776461   
...         ...       ...       ...  ...       ...       ...       ...   
17332  0.601497  0.102205  0.044518  ... -0.415398 -0.215571  0.471940   
17333  1.075955  0.971536 -0.056004  ... -0.415398 -0.191915  0.263873   
17334 -2.221331 -2.683164  1.971993  ... -0.415398 -0.475789 -0.568394   
17335 -0.062259  0.300681 -0.773981  ...  1.510721  5.556521  0.055806   
17336  0.283588 -0.840359 -0.469561  ... -0.415398 -0.452132 -0.776461   

            128       129       130       131       132       133  label  
0     -0.159069 -0.338560 -0.322463 -0.143152 -1.080384  0.538832      0  
1     -0.159069 -0.338560 -0.322463 -0.143152 -0.973158  0.538832      1  
2     -0.159069  1.815429 -0.322463 -0.143152 -0.865932  0.538832      8  
3     -0.159069  1.456431 -0.322463 -0.143152 -0.758705  0.538832      5  
4     -0.159069 -0.338560 -0.322463 -0.143152 -0.651479  0.538832      9  
...         ...       ...       ...       ...       ...       ...    ...  
17332 -0.159069 -0.338560 -0.322463 -0.143152  0.099106  0.538832      1  
17333 -0.159069 -0.338560 -0.322463 -0.143152  0.206332  0.538832      1  
17334 -0.159069 -0.338560 -0.322463 -0.143152  0.313558  0.538832      2  
17335 -0.159069  0.379436 -0.322463 -0.143152  0.420785  0.538832      1  
17336 -0.159069 -0.338560 -0.322463 -0.143152  0.528011  0.538832      0  

[17337 rows x 135 columns]

In [8]:
df.std()

0        1.000029
1        1.000029
2        1.000029
3        1.000029
4        1.000029
           ...   
130      1.000029
131      1.000029
132      1.000029
133      1.000029
label    4.172304
Length: 135, dtype: float64

In [9]:
x = df.drop('label',axis=1)
y = df['label']

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)


In [11]:
x_scaled.mean(axis=0)

array([-1.39346213e-17,  2.41806664e-17,  4.09841804e-18,  1.51641468e-17,
       -6.96731067e-18, -6.96731067e-18, -9.63128240e-18,  1.10657287e-17,
       -1.72133558e-17, -1.43444631e-17,  1.96211764e-17, -1.43444631e-18,
       -1.06558869e-17,  1.47543049e-17, -1.27050959e-17, -8.19683608e-18,
        0.00000000e+00,  1.31149377e-17, -1.38321609e-17,  2.84840054e-17,
        3.27873443e-18, -1.98260973e-17, -1.08608078e-17,  2.45905082e-18,
        1.35247795e-17,  4.50825985e-18, -2.57175732e-17, -1.45493840e-17,
       -9.83620330e-18,  1.39346213e-17,  3.27873443e-17,  1.51641468e-17,
       -1.09632683e-17, -2.47954291e-17, -3.07381353e-18, -5.94270616e-18,
        1.39346213e-17,  1.96724066e-17,  1.63936722e-17, -9.73374285e-18,
        2.52052710e-17, -1.38321609e-17,  1.14755705e-17, -1.51641468e-17,
        2.04920902e-18, -2.00822484e-17, -2.56151128e-18,  1.53690677e-17,
       -5.73778526e-18, -8.19683608e-18, -2.82790845e-17,  2.21314574e-17,
       -1.63936722e-18, -

In [12]:
x_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=101)

In [14]:
from sklearn.linear_model import LinearRegression
std_model = LinearRegression()
std_model.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred = std_model.predict(x_test)
pd.DataFrame({'y_test': y_test,'y_pred': y_pred})

y_test    y_pred
9941       10  3.771601
721        14  4.939665
13668       1  0.725771
3193        1  1.931905
15922       9  7.579870
...       ...       ...
16967       7  2.917204
8031        6  5.227923
5714        5  3.926334
2770        1  3.264886
8119        9  3.249419

[3468 rows x 2 columns]

In [16]:
r2score = std_model.score(x_test,y_test)
print(r2score)

0.5057606728297402


In [17]:
X = df.iloc[:,[16,83,105,118]]
Y = df['label']

In [18]:
print(X)
print(Y)

             16        83       105      118
0      0.275910 -2.560023 -0.943919 -0.07655
1      0.410288 -2.560023 -0.943919 -0.07655
2      0.368094 -2.560023 -0.943919 -0.07655
3     -0.418360 -2.560023 -0.943919 -0.07655
4     -2.347797 -2.560023 -0.943919 -0.07655
...         ...       ...       ...      ...
17332  0.368094  0.684935 -1.528547 -0.07655
17333 -0.607199  0.684935 -1.528547 -0.07655
17334  0.687944  0.304160  1.411413 -0.07655
17335  1.258476  0.304160  1.411413 -0.07655
17336 -0.237695  0.304160  1.411413 -0.07655

[17337 rows x 4 columns]
0        0
1        1
2        8
3        5
4        9
        ..
17332    1
17333    1
17334    2
17335    1
17336    0
Name: label, Length: 17337, dtype: int64


In [19]:
X_scaled = scaler.fit_transform(X)

In [20]:
X_scaled.mean(axis=0)


array([0., 0., 0., 0.])

In [21]:
X_scaled.std(axis=0)

array([1., 1., 1., 1.])

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_scaled,Y,test_size=0.2,random_state=101)

In [23]:
from sklearn.linear_model import LinearRegression
std_model = LinearRegression()
std_model.fit(X_train,Y_train)

LinearRegression()

In [24]:
Y_pred = std_model.predict(X_test)
pd.DataFrame({'Y_test': Y_test,'Y_pred': Y_pred})

Y_test    Y_pred
9941       10  6.320779
721        14  5.783288
13668       1  4.968002
3193        1  6.971853
15922       9  8.801519
...       ...       ...
16967       7  7.535065
8031        6  4.850704
5714        5  6.422546
2770        1  6.916729
8119        9  4.968002

[3468 rows x 2 columns]

In [25]:
r2score = std_model.score(X_test,Y_test)
print(r2score*100,'%')

5.856915473770819 %


In [26]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor()
forest_model.fit(X_train,Y_train)

RandomForestRegressor()

In [27]:
forest_pred = forest_model.predict(X_test)
pd.DataFrame({'y_test': Y_test,'forest_pred': forest_pred})

y_test  forest_pred
9941       10     4.087946
721        14     3.045974
13668       1     1.789870
3193        1     1.120000
15922       9     7.900000
...       ...          ...
16967       7     1.952857
8031        6     1.176833
5714        5     4.203728
2770        1     2.786345
8119        9     1.789870

[3468 rows x 2 columns]

In [28]:
r2score = forest_model.score(X_test,Y_test)
print(r2score)

0.5568339872279932


In [29]:
forest_model.fit(x_train,y_train)

Y_pred = forest_model.predict(x_test)
pd.DataFrame({'y_test': y_test,'Y_pred': Y_pred})

r2score = forest_model.score(x_test,y_test)
print(r2score)

0.7493246549875168
